language: python
python: 
  - 3.6
  - 3.6-dev
  - 3.7-dev
env:
  - TESTING=1 SCRIPT='pytest -v --cov http_firewall --cov-report term-missing'
install:
  - pip install -r requirements.dev.txt
  - pip install -r requirements.test.txt
  - pip install -e .
jobs:  
  include:
    - stage: "lint"
      matrix:
        include:
          - python: 3.6
      env: 
        - TESTING=0 SCRIPT="python setup.py lint"

after_success:
  - "[[ $TESTING -eq 1 ]] && coveralls"
deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    user: mikeshultz
    password:
      secure: "b2WZbkAHtLgy4sCGz4TI3z134AvJpGUD1zwqWDwTJrGLvcq5m0RmmZFEAXybJX3lbhKSaGx6GJ8BWkPZQnV7f7Hoo6Rzoh6RrTfTk+VjvRAVJLAkydejGEvpvdlf1ZqhwryC+chdGCGO37Cbpkggjkoc5dLxDOpnTgsfiu8DzqrluadoSp9sTvkg8JDLtps6pDJasN5qrJaHglK3dSPw9yUd8GRw+3+qgVO2MwJ6eAHBEJsyE5H0RHW/oihAx1OFLDUYXfD/tAhSmxU8DtCQ9fSQl67BBZaZVpH/zjVPGb+WuLjgiLQn1El5YQ59OLo+R1bdRGOZ9lBX9Z9Br87Ta9zBCmWLBp7DZmkhRKcb7iNIDkPFjBtOH67B42f1XwnfTaWnoABuDIMYgVvMvsZ+zFKGpsBEgAB2ukBqcX5Ekmr230Jf6e0yn80uvi1iegiVq/s6OcUbpOJhBexPb5ZQIKI62AjorLfcwubHNfHEEA4Wi7mdvRanqtHvS82Ar3/dHYmbRpLPk1O8Pef9fc/nPWIWEMiSDy3OdjFiw3p4w7TEUiZvCNz2nsa+8tlp+8BizQKCo6zDyOKA06kXZIyTgrDg1Lri0/cO/jFXyJdC5L+y2UcwmBiCvEkuIbqazEqNoJWxxojAkKI4K+YM7Q5f46BeCBZL2HstIQrRZ3C62CE="
    skip_existing: true
    on:
      tags: true
      python: 3.6
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+[ab]{0,1}[0-9]*$
  - provider: pypi
    user: mikeshultz
    password:
      secure: "hy2YF83Nu9iOBDpDn1FEjXR5MDq5Wodf6JEhy9FB+l7yi2M6czuL/e8+anz5WjdbiPA21OYJiBSqTKyyeFRmRlDkbZEYbajYVPe9D9s1P7qylr5s2K6l9QvIm3mV+6G4ilmiGaBmacyPOLOl9LkDVPvUAiMFJmjMi/phOFbI/2I7zXc4eYb0oETKgKT3SWG1pDc2iS5D/Cbg64hZ85C/nFaIBe4j/fWilP2paf5CJ7qL6QzdFBZxOIYBkdRLKh9BsNQM5ILk0yvQZxKh7I8X4a3bYdL4nAUQiTIw/XiP+47RGfQWAm8N3vAfotI+4TkLn259OD80cKHAQ8om5hPWWXnOPB4zNoLsVO/T9HmjK1U55QOpTEbwESANBo0sNvU4IgEOX+5qJ1aJOiT/k8XbVPTkT7oOdwCOJs6vpm3SPBX+69WvzZjcAK5iHrkj9ajZpjQcrgMHeQGqAYqGWtEcgCgNL7CcwE0RL0cyoqEpcPY7JDrsB2BN7/h9GkPu2jaT6xJyAagiw4j13MUL9APN362DUYFtKNVdFkmIyG5us0P0719T+dP7Le4Btie600jG+VdJNTsf/BIEmR86DIfBa1ODcPWyAIlpo5kqvNcaj522L9ZK2xFmpcOcTBBJjEeocmVINTvmpWov9t/jhhIbqsI8Sf3wBDovduRtNk6r/pU="
    skip_existing: true
    on:
      tags: true
      python: 3.6
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
script: $SCRIPT
